[package]
name = "matasano"
version = "0.0.1"
authors = [ "Kyle Aleshire <kjaleshire@gmail.com>" ]

[lib]
name = "matasano"
path = "src/lib.rs"
test = false

[dependencies]
rand = "0.3.14"
rust-crypto = "0.2.35"
rustc-serialize = "0.3.19"
url = "1.1.0"
